version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb2
    volumes:
      - mongodb_data:/app/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    

volumes:
  mongodb_data: